import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
import { createHash } from "crypto";
import { createUser, findUserByEmail } from "../repository/user.repository.js";
import { redisClient } from "../utils/db.utils.js";

const hashId = (id) => {
    return createHash("sha256").update(String(id)).digest("hex");
};

const createTokens = (payload) => {
    const accessToken = jwt.sign(payload, process.env.JWT_SECRET, { expiresIn: "15m" });
    const refreshToken = jwt.sign(payload, process.env.JWT_SECRET, { expiresIn: "7d" });
    return { accessToken, refreshToken };
}

export const registerUser = async (username, email, password) => {
    try {        
        const existing = await findUserByEmail(email);
        if (existing) {
            throw new Error("Email already in use");
        }

        // hash the password
        const passwordHash = await bcrypt.hash(password, 10);
        const id = Date.now(); // in real app, generated by your database
        const userData = { username, email, passwordHash, id };
        const user = await createUser(userData);
        const { accessToken, refreshToken } = createTokens({ id, email });
        const hashedId = hashId(id);
        await redisClient.set(hashedId, refreshToken, { EX: 7 * 24 * 60 * 60 });
        return { ...user, accessToken, refreshToken };
    } catch (error) {
        console.error("Error registering user:", error);
        throw error;
    }  
};

export const loginUser = async (email, password) => {
    try {
        const user = await findUserByEmail(email);
        if (!user) {
            throw new Error("Invalid credentials");
        }
        const passwordMatch = await bcrypt.compare(password, user.passwordHash);
        if (!passwordMatch) {
            throw new Error("Invalid credentials");
        }
        const { accessToken, refreshToken } = createTokens({ id: user.id, email: user.email });
        const hashedId = hashId(user.id);
        await redisClient.set(hashedId, refreshToken, { EX: 7 * 24 * 60 * 60 });
        return { ...user, accessToken, refreshToken };
    } catch (error) {
        console.error("Error logging in user:", error);
        throw error;
    }
};

export const logoutUser = async (userId) => {
    try {
        const hashedId = hashId(userId);
        await redisClient.del(hashedId);
    } catch (error) {
        console.error("Error logging out user:", error);
        throw error;
    }
};

export const refreshToken = async (token) => {
    try {
        const decoded = jwt.verify(token, process.env.JWT_SECRET);
        const hashedId = hashId(decoded.id);
        const stored = await redisClient.get(hashedId);
        if (!stored || stored !== token) {
            throw new Error("Refresh token not recognized");
        }
        const { accessToken, refreshToken } = createTokens({ id: decoded.id, email: decoded.email });
        await redisClient.set(hashedId, refreshToken, { EX: 7 * 24 * 60 * 60 });
        return { accessToken, refreshToken };
    } catch (error) {
        console.error("Error refreshing token:", error);
        throw error;
    }
};