import { createTripPlan, getPlanById, updateTripPlan, deleteTripPlan } from "../repository/trip-plan.repository.js";
import { trackTripPlan, getTrackedPlansByUserId } from "../repository/user-plans.repository.js";

export const makeNewTripPlan = async (cityName, numberOfDays, budget, userId, coordinates) => {
    try {
    const response = await fetch("http://127.0.0.1:8000/plan-trip", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        cityName,
        numberOfDays,
        budget,
        coordinates,
      }),
    });

    const data = await response.json();
    const planData = data.plans;
    

    // res.json({ plan: data });
    let resPlanData = [];
    for(var plan of planData) {
        const planId = String(Date.now()); // in real app, generated by your database
        plan = { ...plan, planId };
        await createTripPlan(plan);
        await trackTripPlan(userId, planId); // Track the plan for the user
        resPlanData.push(plan);
    }


    return resPlanData;

  } catch (err) {
    console.error(err);
    res.status(400).json({ error: err.message });
  }
};

export const getUserTripPlans = async (userId) => {
    try {
        const tripPlans = await getTripPlanById(userId);
        return tripPlans;
    } catch (error) {
        console.error("Error fetching user's trip plans:", error);
        throw error;
    }
};

export const getTripPlanById = async (id) => {
    try {
        const tripPlan = await getPlanById(id);
        return tripPlan;
    } catch (error) {
        console.error("Error fetching trip plan by ID:", error);
        throw error;
    }
};

export const updateExistingTripPlan = async (id, updateData) => {
    try {
        const updatedTripPlan = await updateTripPlan(id, updateData);
        return updatedTripPlan;
    } catch (error) {
        console.error("Error updating trip plan:", error);
        throw error;
    }
};

export const deleteExistingTripPlan = async (id) => {
    try {
        await deleteTripPlan(id);
    } catch (error) {
        console.error("Error deleting trip plan:", error);
        throw error;
    }
};

export const getUserTrackedPlans = async (userId) => {
    try {
        const trackedPlans = await getTrackedPlansByUserId(userId);
        return trackedPlans;
    } catch (error) {
        console.error("Error fetching user's tracked plans:", error);
        throw error;
    }
};

