import { createTripPlan, getPlanById, updateTripPlan, deleteTripPlan } from "../repository/trip-plan.repository.js";
import { trackTripPlan, getTrackedPlansByUserId } from "../repository/user-plans.repository.js";

const normalizeTouristSpots = (spots) => {
  if (!Array.isArray(spots)) return [];
  return spots.map((spot) => {
    if (typeof spot === "string") {
      return { name: spot };
    }
    return spot;
  });
};

export const makeNewTripPlan = async (cityName, numberOfDays, budget, userId, coordinates) => {
  try {
    const response = await fetch("http://TAPlanneragent:8000/plan-trip", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        cityName,
        numberOfDays,
        budget,
        coordinates,
      }),
    });

    const data = await response.json();
    const planData = Array.isArray(data.plans) ? data.plans : [];

    let resPlanData = [];
    for (const plan of planData) {
      const planId = String(Date.now()); // in real app, generated by your database
      const normalizedPlan = {
        ...plan,
        planId,
        tourist_spots: normalizeTouristSpots(plan.tourist_spots),
      };
      await createTripPlan(normalizedPlan);
      await trackTripPlan(userId, planId); // Track the plan for the user
      resPlanData.push(normalizedPlan);
    }

    return resPlanData;
  } catch (err) {
    console.error(err);
    throw err;
  }
};

export const getUserTripPlans = async (userId) => {
    try {
        const tripPlans = await getTripPlanById(userId);
        return tripPlans;
    } catch (error) {
        console.error("Error fetching user's trip plans:", error);
        throw error;
    }
};

export const getTripPlanById = async (id) => {
    try {
        const tripPlan = await getPlanById(id);
        return tripPlan;
    } catch (error) {
        console.error("Error fetching trip plan by ID:", error);
        throw error;
    }
};

export const updateExistingTripPlan = async (id, updateData) => {
    try {
        const updatedTripPlan = await updateTripPlan(id, updateData);
        return updatedTripPlan;
    } catch (error) {
        console.error("Error updating trip plan:", error);
        throw error;
    }
};

export const deleteExistingTripPlan = async (id) => {
    try {
        await deleteTripPlan(id);
    } catch (error) {
        console.error("Error deleting trip plan:", error);
        throw error;
    }
};

export const getUserTrackedPlans = async (userId) => {
    try {
        const trackedPlans = await getTrackedPlansByUserId(userId);
        return trackedPlans;
    } catch (error) {
        console.error("Error fetching user's tracked plans:", error);
        throw error;
    }
};

