import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
import { createHash } from "crypto";
import { createTripPlan, getPlanById, updateTripPlan, deleteTripPlan } from "../repository/trip-plan.repository.js";
import { trackTripPlan } from "../repository/user-plans.repository.js";


export const makeNewTripPlan = async (cityName, numberOfDays, budget, userId) => {
    try {
    const PROMPT_TEMPLATE = `Create a detailed travel plan for a trip to ${cityName} lasting ${numberOfDays} 
        days with a budget of ${budget} INR. The places to visit should be in top tourist locations.`;
    const response = await fetch("http://127.0.0.1:8000/plan-trip", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        city: cityName,
        question: PROMPT_TEMPLATE,
      }),
    });

    const data = await response.json();

    // res.json({ plan: data });

    const planId = String(Date.now()); // in real app, generated by your database

    const tripPlan = await createTripPlan({ ...data, planId });
    await trackTripPlan(userId, planId); // Track the plan for the user
    return tripPlan;

  } catch (err) {
    console.error(err);
    res.status(400).json({ error: err.message });
  }
};

export const getUserTripPlans = async (userId) => {
    try {
        const tripPlans = await getTripPlanById(userId);
        return tripPlans;
    } catch (error) {
        console.error("Error fetching user's trip plans:", error);
        throw error;
    }
};

export const getTripPlanById = async (id) => {
    try {
        const tripPlan = await getPlanById(id);
        return tripPlan;
    } catch (error) {
        console.error("Error fetching trip plan by ID:", error);
        throw error;
    }
};

export const updateExistingTripPlan = async (id, updateData) => {
    try {
        const updatedTripPlan = await updateTripPlan(id, updateData);
        return updatedTripPlan;
    } catch (error) {
        console.error("Error updating trip plan:", error);
        throw error;
    }
};

export const deleteExistingTripPlan = async (id) => {
    try {
        await deleteTripPlan(id);
    } catch (error) {
        console.error("Error deleting trip plan:", error);
        throw error;
    }
};

